### ISSUE TITLE
New install of emu fails to run most device commands

### ISSUE THREAD

**Issue by SgtPooki** [emu-sh/.oh-my-comma#68]
# `emu device`: 📈 Statistics about your device
```bash
comma@tici:/data/openpilot$ emu device
❌ You must specify a command for emu device. Some options are:
- emu device battery: 🔋 see information about the state of your battery
- emu device reboot: ⚡ safely reboot your device
- emu device shutdown: 🔌 safely shutdown your device
  >>  Arguments 💢:
    - -r, --reboot: An alternate way to reboot your device

- emu device settings: ⚙️ open the Settings app
  >>  Arguments 💢:
    - -c, --close: Closes the settings application
```
# `emu device battery`: 🔋 see information about the state of your battery
```bash
comma@tici:/data/openpilot$ emu device battery
Traceback (most recent call last):
  File "/data/community/.oh-my-comma/emu.py", line 42, in <module>
    emu = Emu(args)
  File "/data/community/.oh-my-comma/emu.py", line 23, in __init__
    self.parse()
  File "/data/community/.oh-my-comma/emu.py", line 33, in parse
    self.commands[cmd].main(self.args, cmd)
  File "/data/community/.oh-my-comma/commands/base.py", line 22, in main
    self.start_function_from_str(cmd)
  File "/data/community/.oh-my-comma/commands/base.py", line 31, in start_function_from_str
    getattr(self, cmd)()  # call command's function
  File "/data/community/.oh-my-comma/commands/device/__init__.py", line 44, in _battery
    r = check_output('dumpsys batterymanager')
  File "/data/community/.oh-my-comma/py_utils/emu_utils.py", line 135, in check_output
    return Output(subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT, encoding='utf8', shell=shell))
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dumpsys'
```
# `emu device reboot`: ⚡ safely reboot your device
```bash
comma@tici:/data/openpilot$ emu device reboot
Traceback (most recent call last):
  File "/data/community/.oh-my-comma/emu.py", line 42, in <module>
    emu = Emu(args)
  File "/data/community/.oh-my-comma/emu.py", line 23, in __init__
    self.parse()
  File "/data/community/.oh-my-comma/emu.py", line 33, in parse
    self.commands[cmd].main(self.args, cmd)
  File "/data/community/.oh-my-comma/commands/base.py", line 22, in main
    self.start_function_from_str(cmd)
  File "/data/community/.oh-my-comma/commands/base.py", line 31, in start_function_from_str
    getattr(self, cmd)()  # call command's function
  File "/data/community/.oh-my-comma/commands/device/__init__.py", line 39, in _reboot
    check_output('am start -a android.intent.action.REBOOT')
  File "/data/community/.oh-my-comma/py_utils/emu_utils.py", line 135, in check_output
    return Output(subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT, encoding='utf8', shell=shell))
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'am'
```
# `emu device shutdown`: 🔌 safely shutdown your device
```bash
comma@tici:/data/openpilot$ emu device shutdown
Traceback (most recent call last):
  File "/data/community/.oh-my-comma/emu.py", line 42, in <module>
    emu = Emu(args)
  File "/data/community/.oh-my-comma/emu.py", line 23, in __init__
    self.parse()
  File "/data/community/.oh-my-comma/emu.py", line 33, in parse
    self.commands[cmd].main(self.args, cmd)
  File "/data/community/.oh-my-comma/commands/base.py", line 22, in main
    self.start_function_from_str(cmd)
  File "/data/community/.oh-my-comma/commands/base.py", line 31, in start_function_from_str
    getattr(self, cmd)()  # call command's function
  File "/data/community/.oh-my-comma/commands/device/__init__.py", line 34, in _shutdown
    check_output('am start -n android/com.android.internal.app.ShutdownActivity')
  File "/data/community/.oh-my-comma/py_utils/emu_utils.py", line 135, in check_output
    return Output(subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT, encoding='utf8', shell=shell))
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'am'
```
# `emu device settings`: ⚙ open the Settings app
```bash
comma@tici:/data/openpilot$ emu device settings
Traceback (most recent call last):
  File "/data/community/.oh-my-comma/emu.py", line 42, in <module>
    emu = Emu(args)
  File "/data/community/.oh-my-comma/emu.py", line 23, in __init__
    self.parse()
  File "/data/community/.oh-my-comma/emu.py", line 33, in parse
    self.commands[cmd].main(self.args, cmd)
  File "/data/community/.oh-my-comma/commands/base.py", line 22, in main
    self.start_function_from_str(cmd)
  File "/data/community/.oh-my-comma/commands/base.py", line 31, in start_function_from_str
    getattr(self, cmd)()  # call command's function
  File "/data/community/.oh-my-comma/commands/device/__init__.py", line 26, in _settings
    check_output('am start -a android.settings.SETTINGS')
  File "/data/community/.oh-my-comma/py_utils/emu_utils.py", line 135, in check_output
    return Output(subprocess.check_output(cmd, cwd=cwd, stderr=subprocess.STDOUT, encoding='utf8', shell=shell))
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/pyenv/versions/3.8.5/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'am'
```
# emu version:
```bash
comma@tici:/data/openpilot$ emu update
Already up to date.

✅ Successfully updated emu utilities!

Updated /data/community/.oh-my-comma
====== FROM ======
Version v0.1.17 | branch master | remote https://github.com/emu-sh/.oh-my-comma.git
Version v0.1.17 | branch master | remote https://github.com/emu-sh/.oh-my-comma.git
======= TO =======
comma@tici:/data/openpilot$
```

**Comment by SgtPooki** [comment]
I have the comma3

**Comment by NoahFriendo** [comment]
Same issue here, also running on a comma3.

**Comment by sshane** [comment]
Can someone try this branch out? https://github.com/emu-sh/.oh-my-comma/pull/69
